// Auto-generated by bin/bump-version. Do not edit by hand —
// run `./bin/bump-version` (or `npm version`-style equivalents) instead.
export const VERSION = {
  build: 54,
  version: "2026.05.54",
  builtAt: "2026-05-11T17:49:54Z",
};
