// Auto-generated by bin/bump-version. Do not edit by hand —
// run `./bin/bump-version` (or `npm version`-style equivalents) instead.
export const VERSION = {
  build: 75,
  version: "2026.05.75",
  builtAt: "2026-05-12T14:49:50Z",
};
