// Auto-generated by bin/bump-version. Do not edit by hand —
// run `./bin/bump-version` (or `npm version`-style equivalents) instead.
export const VERSION = {
  build: 69,
  version: "2026.05.69",
  builtAt: "2026-05-11T23:32:05Z",
};
